### ISSUE TITLE
custom standard date format variable for CalenderLocale

### ISSUE THREAD

**Issue by havi05** [peterhoglund/Calendar-Library#2]
The standard date format is different in other languages for example:
- MM/DD/YY is used in the us
- DD/MM/YY is used in germany 

Would it be possible for you to add a variable to set the standard date format ([calender.gd L557](https://github.com/peterhoglund/Calendar-Library/blob/70f6ff1a81648ea7a0def659cf100eada359bcb4/addons/calendar_library/calendar.gd#L557)) in the calender_local.gd file to automatically change the standard format `"%Y-%m-%d"` to the one in the language file?
It could be set using `cal.get_date_formatted(date.year, date.month, date.day, cal.translated_date_standard_format)` for example.
(`cal` is the Calender instance; `translated_date_standard_format` is a new variable in the Calender class)

What do you think?

**Comment by peterhoglund** [comment]
This is a good idea! I can see two ways of doing it. Either with the posix-system as you suggest or with set of predefined formats the user can choose from in a dropdown. Although the posix-system is very flexible it is not user friendly and the complexity is probably not needed only to set the standard date format.

**Comment by havi05** [comment]
A set of predefined formats would also be fine, but I just want to use the `TranslationServer.set_locale(local:string)` to change the local and `TranslationServer.get_locale()` to load the date format known to the user without him having to enter it. 

--------
Example:
```
 TranslationServer.set_locale("de")
 cal.set_calendar_locale("res://addons/calendar_library/demo/calendar_locale_"+TranslationServer.get_locale()+".tres")
 cal.translated_date_standard_format 
```

Therefor it would need a defined variable in the locales file to call the standard format from the predefined list. (So the code can select the correct format )

**Comment by peterhoglund** [comment]
This is what I would like to do. I'm adding two fields to the CalendarLocale resource: `date_format` and `divider_symbol`. `date_format` can be set to YMD, DMY, MDY or YDM, `divider_symbol` can be set to any characters. Then you call `get_date_locale_format(year, month, day, four_digit_year = true)` from the Calendar object to get a formatted string based on the current locale's `date_format`, i.e 2024-02-08 for YMD and "-" or 02/08/24 for MDY "/" and `four_digit_year` set to false. I hope this solves your needs.

**Comment by havi05** [comment]
That would be exactly what I need.
For the german local file the `date_format` would be DMY and the `divider_symbol` would be `.`

Thank you very much.

**Comment by peterhoglund** [comment]
Great! I'll commit it in the evening :)

**Comment by peterhoglund** [comment]
The date format is in, let me know is something doesn't seem to work as expected.

**Comment by havi05** [comment]
Thank you very much!
I will try it tomorrow.

**Comment by havi05** [comment]
Thank you, it works perfectly!
