### ISSUE TITLE
2024-11-10 becomes Sun, 1 Nov with POSIX String "%a, %-d %b"

### ISSUE THREAD

**Issue by nudescendantunescalier** [peterhoglund/Calendar-Library#4]
Reason seems to be line 571 in calendar.gd:

`	"%-d": func(y, m, d): return str(d).replace("0", ""),`

Same probably applies to the same replace for "%-m"

Replace removes all occurences of 0, not just the first one.

https://docs.godotengine.org/en/stable/classes/class_string.html#class-string-method-replace

**Comment by peterhoglund** [comment]
Thank you for letting me know! It should now be fixed (changed `replace("0", "")` to `lstrip("0")`.
